# Source: https://gitlab.archlinux.org/archlinux/archlinux-docker/-/blob/master/README.md
# Retrieved: 2026-10-05
ARCH_CI_IDENTITY_REGEXP='https://gitlab\.archlinux\.org/archlinux/archlinux-docker//\.gitlab-ci\.yml@refs/tags/v[0-9]+\.0\.[0-9]+'
ARCH_CI_ISSUER='https://gitlab.archlinux.org'
